### ISSUE TITLE
No license specified in this repository

### ISSUE THREAD

**Issue by reosablo** [y2361547758/hca.js#4]
Do you have any plans to declare a license of this repository?

I'm interested in this library and I want to use your TypeScript or JavaScript codes in my project.
But there are no license specified for now, so their all rights are reserved by you.

I'm glad if you consider to add open source license like MIT.

**Comment by y2361547758** [comment]
This code is under refacting (see #1).

You can use this repo as MIT now, and I would try to review and merge the PR soon.

**Comment by reosablo** [comment]
@y2361547758 
> This code is under refacting (see https://github.com/y2361547758/hca.js/pull/1).
>
> You can use this repo as MIT now, and I would try to review and merge the PR soon.

Thank you! I understand that.
